version: 0.2

env:
  variables:
    java: corretto8

phases:
  install:
    commands:
    - echo installing maven...
    - apt-get update -y
    - apt-get install -y maven
    - apt install -y openjdk-8-jdk
  build:
    commands:
    - echo building the justiceleague-tracker
    - mvn test
    - mvn surefire-report:report
    - mvn install
reports:
  Junit-reports:
    files:
     - '**/*.xml'
    base-directory: 'target/surefire-reports' 
    file-format: "JUNITXML"
  jacoco-reports:
    files:
      - "target/site/jacoco/index.html"
    
artifacts:
  artifact:
    files:
    - target/*.jar
    - scripts/*.sh
    - appspec.yml
    discard-paths: yes
  artifacttarget:
    files:
    - '**/*'
    base-directory: 'target'

cache:
  paths:
  - '/root/.m2/**/*'
