version: 0.2

env:
  variables:
    java: corretto8

phases:
  install:
    commands:
    - echo installing maven...
    - apt-get update -y
    - apt-get install -y maven
  build:
    commands:
    - echo building the justiceleague-tracker
    - mvn test
    - mvn install
reports:
  Junit-reports:
    files:
      - "target/surefire-reports/*.xml"
  jacoco-reports:
    files:
      - "target/site/jacoco/index.html"
artifacts:
  files:
  - target/*.jar
  - scripts/*.sh
  - appspec.yml
  discard-paths: yes

cache:
  paths:
  - '/root/.m2/**/*'
